(* ::Package:: *)

(* ::Input:: *)
(*Get["C:\\Users\\jurek\\OneDrive\\Namizje\\3. Letnik\\NROR\\2. domaca naloga\\mccpi.nb"*)
(*];*)
(**)
(*(*Dolo\[CHacek]imo \[CapitalSHacek]tevilo naklju\[CHacek]nih to\[CHacek]k*)*)
(*n=10000;*)
(**)
(**)
(**)
(**)
(*VariacijaPi[n]*)
(*VariacijaPi[n_]:=Module[*)
(*(*Za variacijo pi-ja z ve\[CHacek]anjem naklju\[CHacek]nih \[SHacek]tevil*)*)
(*{count,x,y,notr,pi1,tocnPi},*)
(**)
(*count=0;*)
(*notr=0;*)
(*pi1={};*)
(*tocnPi=N[Pi];*)
(**)
(*SeedRandom[123];*)
(**)
(*For[i=1,i<=n,i++,x=RandomReal[1];*)
(*y=RandomReal[1];*)
(*If[x^2+y^2<=1,notr++];*)
(*count++;*)
(*AppendTo[pi1,4 notr/count];];*)
(**)
(**)
(**)
(*ListLinePlot[pi1,PlotRange->{3,3.3},AxesLabel->{"Iteracij [n]","Vrednost Pi-ja"},PlotLabel->"Pribli\[ZHacek]ek za \[Pi] s \[SHacek]tevilom naklju\[CHacek]nih to\[CHacek]k",Epilog->{Red,Line[{{0,tocnPi},{n,tocnPi}}]}]]*)
(**)
(*Clear[tockenotr,tockezuni,naspi,napaka,tocnipi]*)
(*tockenotr=mccpi[n][[1]];*)
(*tockezuni=mccpi[n][[2]];*)
(*tocnipi=N[Pi];*)
(*naspi=4 Length[tockenotr]/(Length[tockenotr]+Length[tockezuni]);*)
(*napaka=Abs[naspi-tocnipi]/tocnipi;*)
(*(*Izpis Napake in vrednosti Pi-ja*)*)
(*Print["Pribli\[ZHacek]ek za \[Pi]:",N[naspi \[RawEscape]]];*)
(*Print["Relativna napaka:",N[napaka]];*)
(*(*Prikaz grafa naklju\[CHacek]nih to\[CHacek]k*)*)
(*Show[*)
(*ListPlot[tockenotr,PlotStyle->{Red},PlotStyle->PointSize[0.02],AspectRatio->1,Frame->True,Axes->False],*)
(*ListPlot[tockezuni,PlotStyle->{Blue},PlotStyle->PointSize[0.02],AspectRatio->1,Frame->True,Axes->False]*)
(*]*)
(**)
(**)
(**)
