(* ::Package:: *)

(* ::Input:: *)
(*mccpi[n_]:=Module[*)
(*{count,x,y,tockenotr,tockezuni},*)
(**)
(*count=0;*)
(*tockenotr={};*)
(*tockezuni={};*)
(**)
(*For[i=1,i<=n,i++,*)
(*x=2*RandomReal[1]-1;*)
(*y=2*RandomReal[1]-1;*)
(**)
(*If[x^2+y^2<=1,AppendTo[tockenotr,{x,y}];,*)
(*AppendTo[tockezuni,{x,y}];];*)
(*count++;];*)
(**)
(*{tockenotr,tockezuni}]*)
(**)


(* ::Input:: *)
(**)
(**)
