(* ::Package:: *)

(* ::Input:: *)
(*Clear[t0,n]*)
(*(*Pribli\[ZHacek]ek funkcije okoli to\[CHacek]ke t0*)*)
(*t0 = 2;*)
(*n = 1000;*)
(**)
(*taylor[t0_,n_]:=Module[*)
(*{f,approx,t},f[t_]:=Sin[t] t^2 Exp[-t];(*Definicija funkcije f(t)*)*)
(*approx=Normal[Series[f[t],{t,t0,n}]];*)
(*Plot[{f[t],approx},{t,0,4},*)
(*PlotRange->All,PlotStyle->{Blue,Red},*)
(*PlotLabel->Row[{"Pribli\[ZHacek]ek n-tega reda, n = ",n}],*)
(*ImageSize->Medium]]*)
(**)
(*Manipulate[taylor[2,n],{n,1,10,1}*)
(*]*)
(**)
